### ISSUE TITLE
Mystery HDF5 I/O problem during common_average_reference() on cloud computing

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#12]
I got this error while using Jetstream cloud desktop. Everything else progresses fine until CAR, which fails, but registers as completed in the logs. I really have no idea where to begin on this error so I'm passing it up here. 

```
In [10]: dat.common_average_reference()                                         
Common Average Referencing...
Problems doing the copy from '/vol_b/DS36_spont_taste_200924_145722/DS36_spont_taste_200924_145722.h5:/ (RootGroup) 'DS36_spont_taste_200924_145722'' to '/vol_b/DS36_spont_taste_200924_145722/tmp.h5:/ (RootGroup) '''
The error was --> <class 'tables.exceptions.HDF5ExtError'>: HDF5 error back trace

  File "H5Dio.c", line 336, in H5Dwrite
    can't write data
  File "H5Dio.c", line 828, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2363, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 3686, in H5D__chunk_lock
    unable to preempt chunk(s) from cache
  File "H5Dchunk.c", line 3352, in H5D__chunk_cache_prune
    unable to preempt one or more raw data cache entry
  File "H5Dchunk.c", line 3203, in H5D__chunk_cache_evict
    cannot flush indexed storage buffer
  File "H5Dchunk.c", line 3123, in H5D__chunk_flush_entry
    unable to write raw data to file
  File "H5Fio.c", line 165, in H5F_block_write
    write through page buffer failed
  File "H5PB.c", line 1028, in H5PB_write
    write through metadata accumulator failed
  File "H5Faccum.c", line 826, in H5F__accum_write
    file write failed
  File "H5FDint.c", line 258, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 811, in H5FD_sec2_write
    file write failed: time = Mon Oct  5 10:44:55 2020
, filename = '/vol_b/DS36_spont_taste_200924_145722/tmp.h5', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x55e96d0ef1c1, total write size = 13868, bytes this sub-write = 13868, bytes actually written = 18446744073709551615, offset = 17924071424

End of HDF5 error back trace

Problems appending the elements
The destination file looks like:
 /vol_b/DS36_spont_taste_200924_145722/tmp.h5 (File) ''
Last modif.: 'Mon Oct  5 10:44:55 2020'
Object Tree: 
/ (RootGroup) ''
/common_average (Group) 'Common average electrodes and signals'
/common_average/common_average_group0 (EArray(117623040,), shuffle, blosc(9)) ''
/common_average/common_average_group1 (EArray(117623040,), shuffle, blosc(9)) ''
/common_average/electrodes_group0 (Array(29,)) ''
/common_average/electrodes_group1 (Array(32,)) ''
/digital_in (Group) ''
/digital_in/dig_in_0 (EArray(117623040,), shuffle, blosc(9)) ''
/digital_in/dig_in_1 (EArray(117623040,), shuffle, blosc(9)) ''
/digital_in/dig_in_2 (EArray(117623040,), shuffle, blosc(9)) ''
/digital_in/dig_in_3 (EArray(117623040,), shuffle, blosc(9)) ''
/digital_in/dig_in_4 (EArray(117623040,), shuffle, blosc(9)) ''
/digital_out (Group) ''
/raw (Group) ''
/raw/amplifier_time (EArray(117623040,), shuffle, blosc(9)) ''
/raw/electrode13 (EArray(117623040,), shuffle, blosc(9)) ''
/raw/electrode15 (EArray(117623040,), shuffle, blosc(9)) ''
/raw/electrode8 (EArray(117623040,), shuffle, blosc(9)) ''
/raw_emg (Group) ''
/referenced (Group) 'Common average referenced signals'
/referenced/electrode0 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode1 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode10 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode11 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode12 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode14 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode16 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode17 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode18 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode19 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode2 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode20 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode21 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode22 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode23 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode24 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode25 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode26 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode27 (EArray(117623040,), shuffle, blosc(9)) ''
/referenced/electrode28 (EArray(56098816,), shuffle, blosc(9)) ''

Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/scripts/ptrepack.py", line 238, in copy_children
    use_hardlinks=use_hardlinks)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/group.py", line 1067, in _f_copy_children
    **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/group.py", line 996, in _f_copy
    overwrite, recursive, createparents, **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/node.py", line 822, in _f_copy
    return self._g_copy(dstparent, dstname, recursive, **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/group.py", line 632, in _g_copy
    self._g_copy_children(new_node, **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/group.py", line 679, in _g_copy_children
    **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/node.py", line 725, in _g_copy_as_child
    recursive=False, _log=False, **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/leaf.py", line 472, in _g_copy
    title, filters, chunkshape, _log, **kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/earray.py", line 255, in _g_copy_with_stats
    object._append(self.__getitem__(tuple(slices)))
  File "tables/hdf5extension.pyx", line 1496, in tables.hdf5extension.Array._append
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 336, in H5Dwrite
    can't write data
  File "H5Dio.c", line 828, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2363, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 3686, in H5D__chunk_lock
    unable to preempt chunk(s) from cache
  File "H5Dchunk.c", line 3352, in H5D__chunk_cache_prune
    unable to preempt one or more raw data cache entry
  File "H5Dchunk.c", line 3203, in H5D__chunk_cache_evict
    cannot flush indexed storage buffer
  File "H5Dchunk.c", line 3123, in H5D__chunk_flush_entry
    unable to write raw data to file
  File "H5Fio.c", line 165, in H5F_block_write
    write through page buffer failed
  File "H5PB.c", line 1028, in H5PB_write
    write through metadata accumulator failed
  File "H5Faccum.c", line 826, in H5F__accum_write
    file write failed
  File "H5FDint.c", line 258, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 811, in H5FD_sec2_write
    file write failed: time = Mon Oct  5 10:44:55 2020
, filename = '/vol_b/DS36_spont_taste_200924_145722/tmp.h5', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x55e96d0ef1c1, total write size = 13868, bytes this sub-write = 13868, bytes actually written = 18446744073709551615, offset = 17924071424

End of HDF5 error back trace

Problems appending the elements

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/bin/ptrepack", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/scripts/ptrepack.py", line 539, in main
    use_hardlinks=True)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tables/scripts/ptrepack.py", line 248, in copy_children
    raise RuntimeError("Please check that the node names are not "
RuntimeError: Please check that the node names are not duplicated in destination, and if so, add the --overwrite-nodes flag if desired. In particular, pay attention that root_uep is not fooling you.

```

**Comment by nubs01** [comment]
From the traceback it looks like there was no space left on the device.
